// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3cnGUuXmV79VIJ19lZ6eSR0b0g4Le4nY',
    appId: '1:444343986249:web:37d9729dd2373499b83798',
    messagingSenderId: '444343986249',
    projectId: 'rei-do-corte-6092c',
    authDomain: 'rei-do-corte-6092c.firebaseapp.com',
    storageBucket: 'rei-do-corte-6092c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5D4I6UJplvqTJhaDn30qk3fq2aL2MBeU',
    appId: '1:444343986249:android:9b5b6e9f2701548bb83798',
    messagingSenderId: '444343986249',
    projectId: 'rei-do-corte-6092c',
    storageBucket: 'rei-do-corte-6092c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByrgVMBPBjWVXJUAaMxhH6AuZ1eItJTQw',
    appId: '1:444343986249:ios:c7cf87ef25452c00b83798',
    messagingSenderId: '444343986249',
    projectId: 'rei-do-corte-6092c',
    storageBucket: 'rei-do-corte-6092c.firebasestorage.app',
    iosBundleId: 'com.example.reiDuCorte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3cnGUuXmV79VIJ19lZ6eSR0b0g4Le4nY',
    appId: '1:444343986249:web:cd0be1d258fe35dcb83798',
    messagingSenderId: '444343986249',
    projectId: 'rei-do-corte-6092c',
    authDomain: 'rei-do-corte-6092c.firebaseapp.com',
    storageBucket: 'rei-do-corte-6092c.firebasestorage.app',
  );

}